version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: mrerenk/aosp
    steps:
      - run: apt update -yqq && apt install -y python3-pip
