version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: mrerenk/aosp
    steps:
      - run:
          name: Update packages
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get update -yqq
            sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -yqq

      - run:
          name: Update git credentials
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"

      - run:
          name: Clone the repository
          command: |
            git clone $REPO_URL $CIRCLE_PROJECT_REPONAME
          environment:
            REPO_URL: https://github.com/MrErenK/circleci/

      - run:
          name: Setup repo and build environment
          command: |
            wget https://storage.googleapis.com/git-repo-downloads/repo
            chmod a+x repo
            sudo install repo /usr/bin/repo

      - run:
          name: Export variables and start the build
          command: |
            cd $CIRCLE_PROJECT_REPONAME
            ls -la
            export should_skip_sync="0"
            export clean_out="0"
            export should_update_trees="0"
            export should_update_kernel="0"
            export installclean="0"
            bash build.sh
