version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: mrerenk/aosp
    steps:
      - run:
          name: Update packages
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get update -yqq
            sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -yqq

      - run:
          name: Verify and update ccache size
          command: |
            ls /mnt/ccache
            ccache -M 75G

      - run:
          name: Update git credentials
          command: |
            git config --global user.name "$CIRCLE_USERNAME"
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"

      - run:
          name: Start the build
          command: |
            cd $CIRCLE_WORKING_DIRECTORY
            bash build.sh
